#+TITLE: Emacs' Preamble
#+AUTHOR: Nikhil Gupta
#+EMAIL: me@nikhgupta.com
#+DATE: 2013-09-21 Sun
#+DESCRIPTION: Configuration for Emacs in a literal-programming (self-documenting) style.
#+KEYWORDS: org babel emacs configuration
#+LANGUAGE: en
#+OPTIONS:   H:3 num:nil toc:2 \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport notangle
#+LINK_UP:
#+LINK_HOME: 
#+STARTUP: hidestars odd overview noinlineimages latexpreview nohideblocks

* Motivation
  
  I have been a long-time [[http://www.vim.org][vim]] user, and started using [[http://gnu.org/s/emacs][Emacs]] because of
  the awesome [[http://orgmode.org][org-mode]] functionality, it provides. Definitely, I have
  been impressed. People were right, for once! I have only been using
  Emacs for a couple of weeks, and I'm already in love with it,
  primarily, because:
  - it has the neatest organizer in this world: the =org-mode=
  - it uses =elisp= to programmatically change itself

  So, soon I was dwelling inside the dark world of getting my new
  editor resonate with myself. I tried several starter packages, viz.:
  - [[http://github.com/bbatsov/prelude][Emacs Prelude]]
  - [[https://github.com/purcell/emacs.d][@purcell's emacs configuration]]
  - [[https://github.com/overtone/emacs-live][Emacs Live]]
  - [[http://eschulte.github.io/emacs24-starter-kit/][Emacs Starter Kit]]

  And, I really enjoyed my couple of days of flirting with these kits,
  and they were really nice, but somehow, they did not represent
  me. My editor felt like someone else' baby in my hands - it was
  adorable, and cute and what not, but it wasn't mine. :)

  So, I started working on my own take at Emacs' configuration, and
  proudly called it [[http://github.com/nikhgupta/preamble][Emacs' Preamble]] - made it, remade it, and remade
  it again and again and each time, I switched the way it represented
  itself. I had already seen [[http://dl.dropboxusercontent.com/u/3968124/sacha-emacs.html][Sacha Chua's Emacs Configuration]], and
  wanted my own to be based upon [[http://orgmode.org/worg/org-contrib/babel/][org-babel]].
